services:
  redis:
    image: redis
    restart: unless-stopped
    # ports:
    #   - 6379:6379

  be:
    image: go-be
    environment:
      - REDIS_HOST=127.0.0.1
      - REQUEST_ORIGIN=http://localhost:5000
    ports:
      - 8080:8080
  fe:
    image: node-fe
    ports:
      - 5000:5000
